export const C = {
  black: '#000000',
  white: '#FFFFFF',
  bg: '#F5F5F5',
  border: '#E5E5E5',
  secondary: '#6B6B6B',
  primary: '#1C1C1E',
  accent: '#D64545',
  // Form / input palette
  inputBg: '#FAFAFA',
  labelText: '#3F3F46',
  placeholder: '#A1A1AA',
  textMuted: '#71717A',
  errorBg: '#FEF2F2',
  errorBorder: '#FECACA',
  // Status palette
  statusDraft: '#9CA3AF',
  statusDraftBg: '#F3F4F6',
  statusPending: '#D97706',
  statusPendingBg: '#FEF3C7',
  statusSubmitted: '#2563EB',
  statusSubmittedBg: '#DBEAFE',
  statusInReview: '#7C3AED',
  statusInReviewBg: '#EDE9FE',
  statusResolved: '#059669',
  statusResolvedBg: '#D1FAE5',
  statusRejected: '#DC2626',
  statusRejectedBg: '#FEE2E2',
  // Priority palette
  priorityLow: '#6B7280',
  priorityLowBg: '#F3F4F6',
  priorityMedium: '#2563EB',
  priorityMediumBg: '#DBEAFE',
  priorityHigh: '#D97706',
  priorityHighBg: '#FEF3C7',
  priorityCritical: '#DC2626',
  priorityCriticalBg: '#FEE2E2',
} as const;
